"""primer commit

Revision ID: 7b36291a687e
Revises: 
Create Date: 2026-04-17 09:42:50.908395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b36291a687e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=250),
               nullable=False)
        batch_op.alter_column('apaterno',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('amaterno',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.alter_column('edad',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('maestros', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('apellidos',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('especialidad',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maestros', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('especialidad',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('apellidos',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('edad',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('amaterno',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('apaterno',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
